config/routes.rb
Whenitopen::Application.routes.draw do
  devise_for :admins

  get "/aboutus" => 'home#aboutus', :as => :aboutus

  get "/contactus" => 'home#contactus', :as => :contactus

  post "/contact" => 'home#contact', :as => :contact

  get "/terms_and_conditions" => 'home#terms_and_conditions', :as => :terms_and_conditions
  root :to => "businesses#index"

  resources :businesses do
    collection do
      get :search
      get :city_businesses
      get :csv
      get :cities
      get :pending_businesses
    end
    member do
      put :confirm_business
    end
  end
  
  resources :imports do
    collection do
      get :import
      post :upload_xls
      get :delete_business
      get :delete_all_by_business_name
    end
  end
  
  resources :recent_add_businesses

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  layout :get_layout
  def index
    if params[:city]
      session[:city] = params[:city]
      session[:state] = params[:state]
    end
    session[:state]
    if request.xhr?
      respond_to do |format|
        format.js
      end
    end
  end
  
  def new
    @business = Business.new
  end
  
  def create
    @business = Business.new(params[:business].reject{ |key, value| value.blank?})
    if @business.save
      @business.update_attribute(:status, 'pending') if !current_admin
      redirect_to imports_path
    end
  end

  def cities
    @cities = Business.select('DISTINCT city,state').where("city LIKE ?", "#{params[:city]}%") 
    respond_to do |format|
      format.js
    end
  end

  def city_businesses
    @name = params[:company_name].split(' and').join(' &')
    @namee = params[:company_name].split(' &').join(' and')
    @cities = Business.select('DISTINCT company_name').where("address IS NOT NULL and (company_name LIKE ? or company_name LIKE ?) and city = ?", "#{@name}%", "#{@namee}%", "#{session[:city]}") 
    respond_to do |format|
      format.js
    end
  end

  def search
    @name = params[:company_name].split(' and').join(' &')
    a = Time.zone.now.strftime("%a").downcase+"_to"
    b = Time.zone.now.strftime("%a").downcase+"_from"
    params[:address].present? ? (@ab_business_databases = Business.search "(^#{params[:company_name]}, #{params[:city]}, #{params[:address]})", :limit => 1) : (@ab_business_databases = Business.search "(^#{@name}$ | (#{@name}), ^#{session[:city]})", :limit => 1)
    @spelling = Business.search_spelling(@name, session[:city]) if @ab_business_databases.empty?
    if @ab_business_databases.present?
      @lat = @ab_business_databases.first.latitude
      @lng = @ab_business_databases.first.longitude
      @categories = Business.near([@lat, @lng],200000, :order =>:distance).where("category = ? and company_name != ? and #{b} <= #{Time.zone.now.strftime("%H").to_i} and #{a} > #{Time.zone.now.strftime("%H").to_i - 12} and address IS NOT NULL and city IS NOT NULL and address != ? and id NOT IN (?)", "#{@ab_business_databases.first.category}", "#{@ab_business_databases.first.company_name}","#{@ab_business_databases.first.address}","#{@ab_business_databases.first.id}").paginate :page => params[:category_page], :per_page => 9
      @locations = Business.near([@lat, @lng],200000, :order =>:distance).where("company_name = ? and id NOT IN (?)", "#{@ab_business_databases.first.company_name}", "#{@ab_business_databases.first.id}").paginate :page => params[:location_page], :per_page => 3
    end
  end
  
  def edit
    @business = Business.find(params[:id])
  end
  
  def update
    @business = Business.find(params[:id])
    if @business.update_attributes(params[:business].reject{ |key, value| value.blank?} )
      @business.update_attribute(:status, 'pending') if !current_admin
      redirect_to edit_business_path(@business)
    end
  end
  
  def pending_businesses
    @businesses = Business.where("status = 'pending'").paginate :page => params[:page], :per_page => 10
  end
  
  def confirm_business
    @business = Business.find(params[:id])
    params[:status] == 'accept' ? (@business.update_attribute(:status, 'confirmed')) : (@business.update_attribute(:status, 'rejected'))
    redirect_to imports_path
  end
  
  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to imports_path
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_category.html.erb
<div id="simresults">
  <% if @categories.present? %>
    <div style="text-align: center;">
      <% @categories.each do |same_category| %>
        <div class="mini_simbox" id="mini_simbox_<%= same_category.id %>" style="cursor: pointer;">
          <a><%= same_category.company_name %></a>
          <br />
          <%= same_category.address %>
          <br />
          <%= same_category.city %>, <%= same_category.state %>
          <br />
          <%= number_to_phone(same_category.phone) %>
          <br />
        </div>
        <script>
          $('#mini_simbox_<%=same_category.id%>').click(function() {
            window.location.href = '<%= search_businesses_path('company_name' => same_category.company_name, :city => same_category.city, :address => same_category.address) %>';
          });
        </script>
      <% end %>
      <div style="clear:both;text-align:right;font-size:14px;padding:10px; padding-right:150px;">
      </div>
    </div>
    <div style="float: right;left: -45px;position: relative;top: -23px;">
      <%= will_paginate @categories, :param_name => 'category_page', :page_links => false, :previous_label => "", :next_label => "" %>
    </div>
  <% else %>
    <p style="text-align: center;">Sorry. There are no similar businesses open right now.</p>
  <% end %>
</div>

app/views/businesses/_city.html.erb
<div>
  <% @cities.each_with_index do |city,index| %>
    <% if city.city.split("'").count == 1 %>
      <%= link_to_function "<div class='citySuggest'>#{city.city.capitalize}, #{city.state}</div>".html_safe ,"text_field_value(this)",:remote => true, :style => 'color: #333333;font-family: arial;font-size: 12px;text-decoration: none;' %>
    <% end %>
  <% end %>
</div>
<script>
  function text_field_value(city) {
    var cit = $(city).text().split(',')[0];
    var sta = $(city).text().split(',')[1];
    $("#city_stater").val($(city).text());
    $("#ajaxcity").hide();
    $.ajax({
      url: '/',
      data: {
        city: cit,
        state: sta
      },
      type: 'GET',
      datatype: 'script',
      success: function(data) {
      }
    });
  }
</script>

app/views/businesses/_city_businesses.html.erb
<div>
  <% @cities.each_with_index do |city,index| %>
    <%= link_to_function "<div class='hint#{index+1}'>#{city.company_name}</div>".html_safe,"text_field_value(this)", :style => 'color: #333333;font-family: arial;font-size: 12px;text-decoration: none;' %>
    <script>
      function text_field_value(city) {
        $("#keywords").val($(city).text());
        $("#ajaxresults").hide();
      }
    </script>
  <% end %>
</div>

app/views/businesses/_geo_plugin.html.erb
<script language="JavaScript" src="http://www.geoplugin.net/javascript.gp" type="text/javascript"></script>
<script type="text/javascript">
  jQuery(document).ready(function($) {
    if ($("#city_stater").val() == ', ') {
      $("#city_stater").val(geoplugin_city() + "," + " " + geoplugin_regionCode());
      $.ajax({
        url: "/",
        data: {
          city: geoplugin_city(),
          state: geoplugin_regionCode()
        },
        type: 'GET',
        success: function(data) {
        }
      });
    } else {
      $("#city_stater").val('<%= session[:city] %>' + "," + " " + '<%= session[:state] %>');
    }
  });
</script>

app/views/businesses/_search.html.erb
<div class="search-part" style="height: 70px;">
  <div style="position: relative;width: 210px;">
    <form id="cityForm" method="post">
      <input id="city_stater" class="city_state" value="<%= session[:city] %>, <%= session[:state] %>" onblur="onBlur(this)" onfocus="onFocus(this)" type="text" style="color:#707070;top: 2px;padding-top: 7px;"/>
    </form>
    <div id="ajaxcity" style="display: none;overflow: auto;max-height: 200px;"></div>
  </div>
  <div class="searchContainer" style="left: 212px;position: relative;top: -50px;width: 340px;">
    <%= form_tag search_businesses_path, :method => :get, :id => "searchForm",:autocomplete => "off" do %>
      <table style="margin: auto;">
        <tbody>
          <tr>
            <td class="home-search">
              <%= text_field_tag :company_name, "",:class=>"textField1",:id => "keywords", :placeholder => 'Enter business name',:onblur => "onBlur(this)", :onfocus => "onFocus(this)",:size => "60px", :style=>"color:#707070;margin:0px -10px 0px 0px;top: -3px;" %>
              <button id="sub" style="background: none; border: none;cursor: pointer;position: absolute;top: 10px;"><%= image_tag("/assets/search_icon.png", :class => 'search-icon', :width => '29', :height => '26', :style => 'top: -1px;') %></button>
            </td>
          </tr>
          <tr>
            <td>
              <div id="ajaxresults" style="display:none;top: 45px;height: 200px;overflow: auto;"></div>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<%= render :partial => 'businesses/geo_plugin' if Rails.env == "production" %>
<script>
        $("#sub").click(function() {
          if ($("#keywords").val() == '') {
            alert("Select Business")
            return false;
          } else {
            $("#searchForm").submit();
          }
        });
</script>

app/views/businesses/_total_search.html.erb
<div class="con-header" style="<%= current_admin ? 'margin-bottom: -30px;' : 'margin-bottom: 15px;'%>">
  <div class="headewrap">
    <div class="logo">
      <%= current_admin ? (link_to image_tag("/assets/when-image-open.png"), imports_path) : (link_to image_tag("/assets/when-image-open.png"), "/") %>
      <%= image_tag("/assets/auto-service-bg.png", :style => 'position: relative;top: 173px;', :id => 'ssss') %>
    </div>
    <%= render :partial => 'businesses/search' %>
    <% if !@ab_business_databases.present? %>
      <% if @spelling %>
        <div style=" float:left; text-align:center; margin-left:305px; margin-top:20px;">
          Did you Mean: <%= link_to @spelling, search_businesses_path(:company_name => @spelling, :city => session[:city]) %>
        </div>
      <% else %>
        <div style=" float:left; text-align:center; margin-left:305px; margin-top:20px;">
          No Results Found.
        </div>
      <% end %>
      <style>
        #footerContentContainer{
          display: none;
        }
      </style>
    <% else %>
      <div class="firstResult">
        <% for business in @ab_business_databases %>
          <div class="closed-auto-service-para">
            <div class="location" style="top: -10px;position: relative; min-height: 165px; font-family:'Arial Black'">
              <div id="0" class="primary_hider" style="padding:0 10px; text-align: center;">
                <div id="main_id0">
                  <div class="spacedout1">
                    <div class="loc_name"><%= business.company_name %></div>
                    <%= business.address %>
                    <br />
                    <%= business.city %>, <%= business.state %>
                    <br />
                    <div class="primephone"><%= number_to_phone(business.phone) %></div>
                    <br />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="hand-icon">
            <%= image_tag("/assets/like-open.png", :width => '44', :height => '17') %>
          </div>
          <% if (business.status != 'pending' and business.status != 'rejected') and !(business.mon_from.blank? and business.tue_from.blank? and business.wed_from.blank? and business.thu_from.blank? and business.fri_from.blank? and business.sat_from.blank? and business.sun_from.blank?) %>
            <span id='holiday_hours'>    
              Holiday hours may vary.
            </span>    
            <div class="red-rib" style="margin-top:5px;">
              <div class="closeOpenLogo" style="display: block;">
                <div id="image_src" style="display: block;"></div>
                <div id="message" style="display: block;padding-top: 9px;">
                  <%= image_tag("/assets/closesin.png") %>
                </div>
                <div id="phone" style="display:none;">905-507-1147</div>
              </div>
              <div class="clockDiv" id="clockDiv">
                <div id="time_left" class="clockStyle"></div>
                <div id="noDayss_<%= Time.zone.now.strftime("%a") %>" style="width:229px;display: none;color: #FFFFFF;font-weight: bold;"></div>
                <div id="noDays_<%= Time.zone.now.strftime("%a") %>" style="width:229px;display: none;color: #FFFFFF;font-weight: bold;">s</div>
              </div>
              <div id="twentyfour" class="twentyfour" style="display: none;margin-top: 12px;">
                <%= image_tag("/assets/247.png") %>
              </div>
            </div>
            <div class="scheduleDiv">
              <%= render :partial => 'timing', :locals => {:business => business} %>
              <div id="schedule1" style="display: none;">
              </div>
              <div style="clear:both;"></div>
            </div>
            <%= render :partial => 'script', :locals => {:business => business} %>
          <% else %>
            <% if business.phone.present? %>
              <div class="red-rib" style="margin-top:34px;margin-left: 40px;">
                <div class="closeOpenLogo" style="display: block;">
                  <div id="phone" style="display: block;"><%= number_to_phone(business.phone) %></div>
                </div>
              </div>
            <% else %>
              <div class="red-ribs" style="margin-top:50px;margin-left: 40px;">
                <div class="closeOpenLogo" style="display: block;">
                </div>
              </div>
            <% end %>
            <script>
              $(document).ready(function() {
                $('body').removeClass('open').addClass('nohour');
                $(".logo a img").attr('src', "/assets/when-image-open.png");
                $("#ssss").attr('src', "/assets/no_hour.png");
                $("#ssss").css({top: 173});
                $(".location").css({top: 10});
                $(".hand-icon img").attr('src', "/assets/like-nohour.png");
                $(".hand-icon").css('padding-top', '145px');
              })
            </script>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div style="clear: both;"></div>
    <% if @ab_business_databases.present? %>
      <% if current_admin %>
        <div id="business_edit1"><%= image_tag("/assets/Edit Button.png", :border=>'0', :width=>"261", :height=>"54") %></div><br />
        <div id="business_edit"><%= link_to "Click here to delete this listing", business_path(business), :method => :delete, :confirm => "Are you sure", :id => 'business_delete' %></div>
      <% else %>
        <% if (business.mon_from.blank? and business.tue_from.blank? and business.wed_from.blank? and business.thu_from.blank? and business.fri_from.blank? and business.sat_from.blank? and business.sun_from.blank?) %>
          <div id="business_edit1" style="margin-bottom: -40px;"><%= image_tag("/assets/Edit Button.png", :border=>'0', :width=>"261", :height=>"54") %></div>
        <% end %>
      <% end %>
      <script>
        $('#business_edit1').click(function() {
          window.location.href = '<%= edit_business_path(business) %>';
        });
      </script>
    <% end %>
  </div>
</div>
<% if @ab_business_databases.present? %>
  <div id="PageContainer">
    <div class="orange">
      <div class="titles">
        <p class="more">Select a Location</p>
        <p style="position: relative;left: 100px;">Open Similar Businesses</p>
      </div>
    </div>
    <div class="mainContainer" style="margin-top:10px;clear:both; ">
      <div class="searchResults">
        <div class="otherResultsContainer" style="height:650px;overflow:hidden;width:240px;">
          <div class="onlyResults">
            <%= render :partial => 'location' %>
          </div>
        </div>
        <div id="category" style="float:right;position:relative;width:700px;">
          <%= render :partial => 'category' %>
        </div>
      </div>
      <div style="clear:both;"></div>
    </div>
  </div>
<% end %>

app/views/businesses/cities.js.erb
$('#ajaxcity').html('<%= escape_javascript render :partial => 'businesses/city' %>');

app/views/businesses/city_businesses.js.erb
$('#ajaxresults').html('<%= escape_javascript render :partial => 'businesses/city_businesses' %>');

app/views/businesses/edit.html.erb
<div class="con-header" style="min-height: 1215px;margin-bottom: 0px;">
  <div class="headewrap">
    <div class="logo">
      <%= current_admin ? (link_to image_tag("/assets/about-logo.png"), imports_path) : (link_to image_tag("/assets/about-logo.png"), "/") %>
    </div>
    <%= render :partial => 'businesses/search' %>
    <div class="firstResult">
      <span id="add_a_listing"><%= image_tag("/assets/edit_a_listing.png")%></span>
      <div class="scheduleDiv" id="add_list_background">
        <div id="schedule0">
          <%= form_for @business, :url => business_path(@business), :html => {:method => 'PUT', :autocomplete => 'off', :onsubmit => "alert('Thank you for contributing to our website. We will review your request and update our website shortly.')"} do |f| %>
            <%= render :partial => 'form', :locals => {:f => f} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/new.html.erb
<div class="con-header" style="min-height: 1215px;margin-bottom: 0px;">
  <div class="headewrap">
    <div class="logo">
      <%= current_admin ? (link_to image_tag("/assets/about-logo.png"), imports_path) : (link_to image_tag("/assets/about-logo.png"), "/") %>
    </div>
    <%= render :partial => 'businesses/search' %>
    <span id="add_a_listing"><%= image_tag("/assets/add_a_listing.png")%></span>
    <div class="firstResult">
      <div class="scheduleDiv" id="add_list_background">
        <div id="schedule0">
          <%= form_for @business, :url => businesses_path(), :html => {:method => 'POST', :autocomplete => 'off', :onsubmit => "alert('Thank you for contributing to our website. We will review your request and update our website shortly.')"} do |f| %>
            <%= render :partial => 'form', :locals => {:f => f} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/pending_businesses.html.erb
<div class="con-header" style="min-height: 500px;height: auto;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="position: relative;top: 120px;width: 99%;padding: 5px;">
    <div style="right: 10px; position: absolute;">
      <%= link_to "Admin Page", imports_path() %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
    <table border="1" width="100%" style="float: left;margin-top: -65px;text-align: center;font-size: 12px;">
      <tr style="font-size: 10px;background-color: #60BED2;">
        <th>Business Name</th>
        <th>Address</th>
        <th>City</th>
        <th>Province</th>
        <th>Mon From</th>
        <th>Mon To</th>
        <th>Tue From</th>
        <th>Tue To</th>
        <th>Wed From</th>
        <th>Wed To</th>
        <th>Thu From</th>
        <th>Thu To</th>
        <th>Fri From</th>
        <th>Fri To</th>
        <th>Sat From</th>
        <th>Sat To</th>
        <th>Sun From</th>
        <th>Sun To</th>
        <th>Actions</th>
      </tr>
      <% for business in @businesses %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td><%= business.company_name %></td>
          <td><%= business.address %></td>
          <td><%= business.city %></td>
          <td><%= business.state %></td>
          <td><%= business.mon_from %></td>
          <td><%= business.mon_to %></td>
          <td><%= business.tue_from %></td>
          <td><%= business.tue_to %></td>
          <td><%= business.wed_from %></td>
          <td><%= business.wed_to %></td>
          <td><%= business.thu_from %></td>
          <td><%= business.thu_to %></td>
          <td><%= business.fri_from %></td>
          <td><%= business.fri_to %></td>
          <td><%= business.sat_from %></td>
          <td><%= business.sat_to %></td>
          <td><%= business.sun_from %></td>
          <td><%= business.sun_to %></td>
          <td>
            <%= link_to "Accept", confirm_business_business_path(business, :status => 'accept'), :method => :put %> |
            <%= link_to "Reject", confirm_business_business_path(business), :method => :put %>
          </td>
        </tr>
      <% end %>
    </table><br />
  </div>
</div>
<style>
  tr.odd{
    background: -moz-linear-gradient(top,  #f8f8f8,  #f6f6f6);
  }
  tr.even{
    background: -moz-linear-gradient(top,  #f2f2f2,  #f0f0f0);
  }
</style>

app/views/businesses/search.html.erb
<%= render :partial => 'total_search' %>

app/views/businesses/search.js.erb
$('#category').html("<%= escape_javascript(render(:partial => '/businesses/category')) %> ");
$('.onlyResults').html("<%= escape_javascript(render(:partial => '/businesses/location')) %> ");