config/routes.rb
Whenitopen::Application.routes.draw do
  devise_for :admins

  get "/aboutus" => 'home#aboutus', :as => :aboutus

  get "/contactus" => 'home#contactus', :as => :contactus

  post "/contact" => 'home#contact', :as => :contact

  get "/terms_and_conditions" => 'home#terms_and_conditions', :as => :terms_and_conditions
  root :to => "businesses#index"

  resources :businesses do
    collection do
      get :search
      get :city_businesses
      get :csv
      get :cities
      get :pending_businesses
    end
    member do
      put :confirm_business
    end
  end
  
  resources :imports do
    collection do
      get :import
      post :upload_xls
      get :delete_business
      get :delete_all_by_business_name
    end
  end
  
  resources :recent_add_businesses

end

app/controllers/recent_add_businesses_controller.rb
class RecentAddBusinessesController < ApplicationController
  before_filter :login?
  def index
    @recent_businesses = RecentAddBusiness.paginate :page => params[:recent_page], :per_page => 10
  end
  
  def new
    @recent_business = RecentAddBusiness.new
  end
  
  def create
    @recent_business = RecentAddBusiness.new(params[:recent_add_business])
    if @recent_business.save
      respond_to do |format|
        format.js
      end
    end
  end
  
  def edit
    @recent_business = RecentAddBusiness.find(params[:id])
  end
  
  def update
    @recent_business = RecentAddBusiness.find(params[:id])
    if @recent_business.update_attributes(params[:recent_add_business])
      respond_to do |format|
        format.js
      end
    end
  end
  
  def destroy
    @recent_business = RecentAddBusiness.find(params[:id])
    @recent_business.destroy
    redirect_to recent_add_businesses_path
  end
end

app/helpers/recent_add_businesses_helper.rb
module RecentAddBusinessesHelper
end

app/views/recent_add_businesses/_edit.html.erb
<div class="con-header" style="min-height: 500px;height: auto;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="left: 500px;position: relative;top: 150px;width: 360px;border: 1px solid black;">
    <%= form_for @recent_business, :url => recent_add_business_path(@recent_business), :html => {:method => 'PUT'}, :remote => true do |f| %>
      <% @recent_business.errors.full_messages.each do |msg| %>
        <ul>
          <li style = 'color: red; list-style: none;'>
            <%= msg %>
          </li>
        </ul>
      <% end %>
      <table cellspacing="5">
        <tr>
          <td>Company Name:</td>
          <td>
            <%= f.text_field :company_name, :placeholder => 'Company Name', :style=>"width: 200px;" %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= submit_tag "Add Recent", :id => 'save_button' %>
          </td>
        </tr>
      </table>
    <%end%>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('body').removeClass('open').addClass('cont');
  })
</script>

app/views/recent_add_businesses/_form.html.erb
<div class="con-header" style="min-height: 500px;height: auto;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="left: 500px;position: relative;top: 150px;width: 360px;border: 1px solid black;">
    <%= form_for @recent_business, :url => recent_add_businesses_path, :html => {:method => 'POST'}, :remote => true do |f| %>
      <% @recent_business.errors.full_messages.each do |msg| %>
        <ul>
          <li style = 'color: red; list-style: none;'>
            <%= msg %>
          </li>
        </ul>
      <% end %>
      <table cellspacing="5">
        <tr>
          <td>Company Name:</td>
          <td>
            <%= f.text_field :company_name, :placeholder => 'Company Name', :style=>"width: 200px;" %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= submit_tag "Add Recent", :id => 'save_button' %>
          </td>
        </tr>
      </table>
    <%end%>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('body').removeClass('open').addClass('cont');
  })
</script>

app/views/recent_add_businesses/_index.html.erb
<div class="con-header" style="min-height: 500px;height: auto;margin-bottom: 0px;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="top: 175px; position: absolute;right: 0px;">
    <%= link_to "Add Recent Business", new_recent_add_business_path %>&nbsp;&nbsp;
  </div>
  <table border="1" width="100%" style="float: left;text-align: center;font-size: 12px;margin-top: 55px;">
    <br /><tr style="font-size: 10px;background-color: #60BED2;">
      <th>Id</th>
      <th>Business Name</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
    <% @recent_businesses.each_with_index do |business,index| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= index+1 %></td>
        <td><%= business.company_name %></td>
        <td><%= business.created_at.strftime("%d-%m-%Y") %></td>
        <td>
          <%= link_to "Edit", edit_recent_add_business_path(business) %> |
          <%= link_to "Delete", recent_add_business_path(business), :method => "DELETE", :confirm => "Are you sure." %>
        </td>
      </tr>
    <% end %>
  </table><br />
  <div style="float: right;position: relative;top: 10px;">
    <%= will_paginate @recent_businesses, :param_name => 'recent_page', :page_links => false, :previous_label => "", :next_label => "" %>
  </div>
</div>
<script>
  $(function() {
    $(".pagination a").click(function() {
      $.getScript(this.href);
      return false;
    });
  });
</script>
<style>
  tr.odd{
    background: -moz-linear-gradient(top,  #f8f8f8,  #f6f6f6);
  }
  tr.even{
    background: -moz-linear-gradient(top,  #f2f2f2,  #f0f0f0);
  }
</style>

app/views/recent_add_businesses/create.js.erb
<% if @recent_business.errors.present? %>
  $("#recent_business").html('<%= escape_javascript render :partial => 'form' %>');
<% else %>
  window.location.href = '<%= recent_add_businesses_path %>';
<% end %>

app/views/recent_add_businesses/edit.html.erb
<div id='edit_recent_business'>
  <%= render :partial => 'edit' %>
</div>

app/views/recent_add_businesses/index.html.erb
<div id="businesses">
  <%= render :partial => '/recent_add_businesses/index' %>
</div>

app/views/recent_add_businesses/index.js.erb
$("#businesses").html('<%= escape_javascript render :partial => 'index' %>');

app/views/recent_add_businesses/new.html.erb
<div id='recent_business'>
  <%= render :partial => 'form' %>
</div>

app/views/recent_add_businesses/update.js.erb
<% if @recent_business.errors.present? %>
  $("#edit_recent_business").html('<%= escape_javascript render :partial => 'edit' %>');
<% else %>
  window.location.href = '<%= recent_add_businesses_path %>';
<% end %>