config/routes.rb
Whenitopen::Application.routes.draw do
  devise_for :admins

  get "/aboutus" => 'home#aboutus', :as => :aboutus

  get "/contactus" => 'home#contactus', :as => :contactus

  post "/contact" => 'home#contact', :as => :contact

  get "/terms_and_conditions" => 'home#terms_and_conditions', :as => :terms_and_conditions
  root :to => "businesses#index"

  resources :businesses do
    collection do
      get :search
      get :city_businesses
      get :csv
      get :cities
      get :pending_businesses
    end
    member do
      put :confirm_business
    end
  end
  
  resources :imports do
    collection do
      get :import
      post :upload_xls
      get :delete_business
      get :delete_all_by_business_name
    end
  end
  
  resources :recent_add_businesses

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_filter :login?
  layout :get_layout
  
  def import
    
  end
  
  def index
    @per_page = params[:per_page] || 10
    @businesses = Business.where("company_name IS NOT NULL and address IS NOT NULL and (status IS NULL or status = 'confirmed')").order('id Desc').paginate(:per_page => @per_page, :page => params[:page])
    @export_businesses = Business.order(:id)
    respond_to do |format|
      format.html
      format.csv {send_data @export_businesses.to_csv, :filename => "Businesses.csv"}
    end
  end
  
  def delete_business
    
  end
  
  def delete_all_by_business_name
    @businesses = Business.where("company_name = ?", "#{params[:company_name]}")
    @businesses.destroy_all
    redirect_to imports_path
  end

  def upload_xls
    if request.post?
      Business.import(params[:file])
      flash[:notice] = "Uploading completed."
      redirect_to imports_path
    else
      flash[:error] = "Failed to Upload a file"
      render :action => 'import'
    end
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_form.html.erb
<div class="con-header" style="min-height: 500px;height: auto;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="left: 500px;position: relative;top: 150px;width: 360px;border: 1px solid black;">
    <%= form_for @recent_business, :url => create_recent_business_imports_path, :html => {:method => 'POST'}, :remote => true do |f| %>
      <% @recent_business.errors.full_messages.each do |msg| %>
        <ul>
          <li style = 'color: red; list-style: none;'>
            <%= msg %>
          </li>
        </ul>
      <% end %>
      <table cellspacing="5">
        <tr>
          <td>Company Name:</td>
          <td>
            <%= f.text_field :company_name, :placeholder => 'Company Name', :style=>"width: 200px;" %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= submit_tag "Add Recent", :id => 'save_button' %>
          </td>
        </tr>
      </table>
    <%end%>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('body').removeClass('open').addClass('cont');
  })
</script>

app/views/imports/_index.html.erb
<div class="con-header" style="min-height: 400px;height: auto;margin-bottom: 0px;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="position: relative;top: 120px;width: 99%;padding-top: 20px;">
    <div id='links' style="right: 10px; position: absolute;">
      <%= link_to "Recent Businesses", recent_add_businesses_path %>
      <%= link_to "Delete Businesses by Business Name", delete_business_imports_path %>
      <%= link_to "Edited Businesses", pending_businesses_businesses_path() %>
      <%= link_to "Add New Business", new_business_path() %>
      <%= link_to "Import Csv", import_imports_path %>
      <%= link_to "Export Csv", imports_path(:format => 'csv') %>
    </div>
    Select: <%= text_field_tag 'per_page', params[:per_page].to_i, :size => 4, :onchange => "if(this.value){window.location='?per_page='+this.value;}" %>
    <table border="1" width="100%" style="float: left;margin-top: -45px;text-align: center;font-size: 12px;">
      <br /><tr style="font-size: 10px;background-color: #60BED2;">
        <th>Business Name</th>
        <th>Address</th>
        <th>City</th>
        <th>Province</th>
        <th>Mon From</th>
        <th>Mon To</th>
        <th>Tue From</th>
        <th>Tue To</th>
        <th>Wed From</th>
        <th>Wed To</th>
        <th>Thu From</th>
        <th>Thu To</th>
        <th>Fri From</th>
        <th>Fri To</th>
        <th>Sat From</th>
        <th>Sat To</th>
        <th>Sun From</th>
        <th>Sun To</th>
        <th>Actions</th>
      </tr>
      <% for business in @businesses %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td><%= business.company_name %></td>
          <td><%= business.address %></td>
          <td><%= business.city %></td>
          <td><%= business.state %></td>
          <td><%= business.mon_from %></td>
          <td><%= business.mon_to %></td>
          <td><%= business.tue_from %></td>
          <td><%= business.tue_to %></td>
          <td><%= business.wed_from %></td>
          <td><%= business.wed_to %></td>
          <td><%= business.thu_from %></td>
          <td><%= business.thu_to %></td>
          <td><%= business.fri_from %></td>
          <td><%= business.fri_to %></td>
          <td><%= business.sat_from %></td>
          <td><%= business.sat_to %></td>
          <td><%= business.sun_from %></td>
          <td><%= business.sun_to %></td>
          <td>
            <%= link_to "Edit", edit_business_path(business) %> |
            <%= link_to "Delete", business_path(business), :method => "DELETE", :confirm => "Are you sure." %>
          </td>
        </tr>
      <% end %>
    </table><br />
  </div>
</div>
<style>
  #footer_page{
    display: none;
  }
  tr.odd{
    background: -moz-linear-gradient(top,  #f8f8f8,  #f6f6f6);
  }
  tr.even{
    background: -moz-linear-gradient(top,  #f2f2f2,  #f0f0f0);
  }

  #links a{
    padding-left: 7px;
  }
</style>

app/views/imports/add_recent_business.html.erb
<div id='recent_business'>
  <%= render :partial => 'form' %>
</div>

app/views/imports/create_recent_business.js.erb
<% if @recent_business.errors.present? %>
  $("#recent_business").html('<%= escape_javascript render :partial => 'form' %>');
<% else %>
  window.location.href = '<%= imports_path %>';
<% end %>

app/views/imports/delete_business.html.erb
<div class="con-header" style="min-height: 500px;height: auto;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="left: 500px;position: relative;top: 150px;width: 400px;border: 1px solid black;">
    <%= form_tag delete_all_by_business_name_imports_path, :method => :get do %>
      <table cellspacing="5" style="width: 400px;">
        <tr>
          <td> <b> Delete All businesses by Business name </b><hr /></td>
        </tr>
        <tr>
          <td>
            Company Name: <%= text_field_tag :company_name,'',:placeholder => "Business Name" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= submit_tag "Delete All", :id => 'save_button' %>
          </td>
        </tr>
      </table>
    <%end%>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('body').removeClass('open').addClass('cont');
  })
</script>

app/views/imports/import.html.erb
<div class="con-header" style="min-height: 500px;height: auto;">
  <div class="headewrap">
    <div class="logo">
      <%= link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path %>
    </div>
    <%= render :partial => 'businesses/search' %>
  </div>
  <div style="left: 500px;position: relative;top: 150px;width: 300px;border: 1px solid black;">
    <%= form_tag upload_xls_imports_path, :multipart => true do %>
      <table cellspacing="5">
        <tr>
          <td> <b> Import the Csv data </b> </td>
        </tr>
        <tr>
          <td>
            <%= file_field_tag :file, :style=>"width: 200px;" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= submit_tag "Import", :id => 'save_button' %>
          </td>
        </tr>
      </table>
    <%end%>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('body').removeClass('open').addClass('cont');
  })
</script>

app/views/imports/index.html.erb
<div id="businesses">
  <%= render :partial => '/imports/index' %>
</div>