config/routes.rb
Whenitopen::Application.routes.draw do
  devise_for :admins

  get "/aboutus" => 'home#aboutus', :as => :aboutus

  get "/contactus" => 'home#contactus', :as => :contactus

  post "/contact" => 'home#contact', :as => :contact

  get "/terms_and_conditions" => 'home#terms_and_conditions', :as => :terms_and_conditions
  root :to => "businesses#index"

  resources :businesses do
    collection do
      get :search
      get :city_businesses
      get :csv
      get :cities
      get :pending_businesses
    end
    member do
      put :confirm_business
    end
  end
  
  resources :imports do
    collection do
      get :import
      post :upload_xls
      get :delete_business
      get :delete_all_by_business_name
    end
  end
  
  resources :recent_add_businesses

end

app/views/layouts/_footer.html.erb
<div id="footerContentContainer">
  <div id="footerContent">
    <div class="footerColumn">
      <h3 class="footerTitle"><img src="/assets/footer-about.png"><span class="footerTitleText">About</span></h3>
      <p class="footerAbout">When is it Open Inc provides you with quick and easy access to business hours across Canada.  We are constantly bringing you more reliable hours of operation for your favourite business locations. </p>
      <p class="footerAbout">Wondering when a business is open? Start your search now.</p>
    </div>
    <div class="footerGutter">
    </div>
    <div class="footerColumn">
      <h3 class="footerTitle"><img src="/assets/footer-twitter.png"><span class="footerTitleText">Twitter <a target="_blank" href="https://twitter.com/WhenisitOpen">@WhenIsItOpen</a></span></h3>
      <%url = "https://twitter.com/WhenisitOpen"%>
      <%doc = Nokogiri::HTML(open(url))%>
      <%@sses = doc.css(".content")[0..1]%>
      <% @sses.each do |item| %>
        <% @content = item.at_css(".tweet-text").text%>
        <% @time = item.at_css(".time").text %>
        <p class="footerTweet"><%= @content %></p>
        <p class="footerTweetDate"><%= @time %></p>
      <% end %>
    </div>
    <div class="footerGutter">
    </div>
    <div class="footerColumn">
      <h3 class="footerTitle"><img src="/assets/footer-added.png"><span class="footerTitleText">Recently Added</span></h3>
      <div class="recentAddedList">
        <p class="recentlyAdded">
          <% RecentAddBusiness.select("distinct company_name").where("company_name IS NOT NULL").order("created_at desc").limit(8).each do |business| %>
            <%= business.company_name %><br />
          <% end %>
        </p>
      </div>    
      <div class="recentAddedList">
        <p class="recentlyAdded">
          <% RecentAddBusiness.select("distinct company_name").where("company_name IS NOT NULL").order("created_at desc").offset(8).limit(8).each do |business| %>
            <%= business.company_name %><br />
          <% end %>
        </p>
      </div>   
    </div>
  </div>
</div>
<div class="footer" style="font-size:13px">
  <div class="footer-inner" style="min-width:1000px; margin:0 auto;">
    <div class="copyright">© When is it Open Inc. 2013</div>
    <div class="footer-menu">
      <ul>
        <li>
          <%= link_to "Add a Listing", new_business_path %>
        </li>
        <li>
          <%= link_to "About Us", aboutus_path %>
        </li>
        <li>
          <%= link_to "Contact Us", contactus_path %>
        </li>
        <li>
          <%= link_to "Terms and Conditions", terms_and_conditions_path %>
        </li>
      </ul>
    </div>
  </div>
</div>
<%= render :partial => '/layouts/google_analytics' if Rails.env == 'production' %>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function() {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date();
    a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

  ga('create', 'UA-45619517-1', 'whenisitopen.ca');
  ga('send', 'pageview');

</script>

app/views/layouts/about.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><%= @title %></title>
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <%= stylesheet_link_tag 'application', :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body class="cont">
    <div id="mainPage" style="min-width: 1000px;width: 100%;">
      <div class="top-head">
        <div class="icons">
          <div class="social">
            <table width="239" border="0">
              <tbody>
                <tr>
                  <% if current_admin %>
                    <%= link_to "Logout", destroy_admin_session_path(), :method => :delete %>
                  <% else %>
                    <td width="65">Like us: </td>
                    <td width="39">
                      <%= link_to image_tag("/assets/h-facebook.png", :width => "32", :height => "32"), "http://www.facebook.com/whenisitopen", :target => "_blank" %>
                    </td>
                    <td width="80">Follow us:</td>
                    <td>
                      <%= link_to image_tag("/assets/h-twitter.png", :width => "32", :height => "32"), "https://twitter.com/WhenisitOpen", :target => "_blank" %>
                    </td>
                  <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="con-header">
        <div class="headewrap">
          <div class="logo">
            <%= current_admin ? (link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), imports_path) : (link_to image_tag("/assets/about-logo.png",:width => "251", :height => "169"), '/') %>
          </div>
          <%= render :partial => 'businesses/search' %>
        </div>
      </div>
      <%= yield %>
      <div id='footer_page'>
        <%= render :partial => '/layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <%= stylesheet_link_tag 'application', :media => "all" %>
    <%= javascript_include_tag "application", 'jquery.autosize.input' %>
    <%= csrf_meta_tag %>
    <title>When Is It Open?</title>
  </head>
  <body class="open">
    <div id="main" style="min-height: 100%; position:relative; background-color:#F3F3F3;">
      <div class="top-head">
        <div class="icons">
          <div class="social">
            <table width="239" border="0">
              <tbody>
                <tr>
                  <% if current_admin %>
                    <td><%= link_to "Logout", destroy_admin_session_path(), :method => :delete %></td>
                  <% else %>
                    <% if (params[:controller] != 'devise/sessions') %>
                      <td width="65">Like us: </td>
                      <td width="39">
                        <%= link_to image_tag("/assets/h-facebook.png", :width => "32", :height => "32"), "http://www.facebook.com/whenisitopen", :target => "_blank" %>
                      </td>
                      <td width="80">Follow us:</td>
                      <td>
                        <%= link_to image_tag("/assets/h-twitter.png", :width => "32", :height => "32"), "https://twitter.com/WhenisitOpen", :target => "_blank" %>
                      </td>
                    <% end %>
                  <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <%= yield %>
      <div id='footer_page'>
        <%= render :partial => '/layouts/footer' if !(params[:controller] == 'devise/sessions' or params[:controller] == 'imports')%>
      </div>
    </div>
  </body>
</html>

app/views/layouts/search.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>When Is It Open?</title>
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <%= stylesheet_link_tag 'application', :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <% ['notice', 'error', 'warning'].each do |f|%>
      <% if flash[f.to_sym]%>
        <script type="text/javascript" >
          jQuery(function() {
            jQuery.notifyBar({
              cls: "<%= f %>",
              html: "<%=  flash[f.to_sym] %>",
              delay: 5000,
              animationSpeed: "normal"
            });
          });
        </script>
      <%end%>
    <%end%>
  </head>
  <body class="home">
    <div class="page-wrap">
      <div id="home-mainPage">
        <div class="home-innerContainer">
          <div class="logoContainer" style="min-height: 265px;">
            <%= image_tag("/assets/logo.png", :width => '355') %>
          </div>
          <%= yield %>
        </div>
      </div>
      <div id='footer_page'>
        <%= render :partial => '/layouts/footer' %>
      </div>
    </div>
  </body>
</html>